spring:
  output:
    ansi:
      enabled: always # 콘솔에서 뜨는 로그에 색이 입혀짐.
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/local;AUTO_SERVER=true
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

logging:
  level:
    '[group.artifact]': DEBUG # 패키지 내 로그는 DEBUG 레벨로 로깅